version: "3"
services:
    app:
        image: golang:1.10
        ports:
            - 8080:8080
        volumes: 
            - .:/go/src/github.com/emptyset/simple-chat
        working_dir: /go/src/github.com/emptyset/simple-chat
        command: go run ./cmd/server/main.go
        depends_on: 
            - database
        networks:
            - internal

    database:
        image: mysql:5.7
        environment:
            MYSQL_DATABASE: "chat"
            MYSQL_ROOT_PASSWORD: "password"
        volumes:
            - ./scripts/users.sql:/docker-entrypoint-initdb.d/users.sql
            - ./scripts/schema.sql:/docker-entrypoint-initdb.d/schema.sql
            - ./data:/var/lib/mysql
        networks:
            - internal

networks:
    internal:
        driver: "bridge"
